---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Order
  labels:
    app: Order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Order
  template:
    metadata:
      labels:
        app: Order
    spec:
      containers:
        - name: Order
          image: username/Order:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: DeliveryStock
  labels:
    app: DeliveryStock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DeliveryStock
  template:
    metadata:
      labels:
        app: DeliveryStock
    spec:
      containers:
        - name: DeliveryStock
          image: username/DeliveryStock:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Order
  labels:
    app: Order
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Order


---


apiVersion: v1
kind: Service
metadata:
  name: DeliveryStock
  labels:
    app: DeliveryStock
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: DeliveryStock

